// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('hello-google', function() {
  this.timeout(30000)
  let driver
  let vars

  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('hello-google', async function() {
      await driver.get('https://www.google.com/');

    let frame = await driver.findElement(By.xpath('//iframe'));
    if(frame){
      await driver.switchTo().frame(frame);

      let button = await driver.wait(until.elementLocated(By.id('introAgreeButton')),5000);
     await button.click();
    }
    

    await driver.switchTo().defaultContent();
    await driver.findElement(By.name('q')).sendKeys('devops', Key.RETURN);
  });
})

